# This is a config for E2B sandbox template.
# You can use template ID (mo655dzl3ewo2w59nq1u) or template name (v0-clone-nextjs-build) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-clone-nextjs-build") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-clone-nextjs-build") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-clone-nextjs-build')

team_id = "72de489b-53a9-45de-b85f-2d8240d17639"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-clone-nextjs-build"
template_id = "mo655dzl3ewo2w59nq1u"
